@startyaml Events-core  
  Events-core:
    description: Lists any significant occurrence or activity that is recorded within
      a patient's health record. Contains information like project ID, donor ID, event
      ID and event type.
    properties:
          project_id:
            description: the unique id provided to the experimental study or project that is governed by an investigator.
            type: string
            example: PROJECT ID is an alphanumeric string that is globally unique identifier for the project or study.
          subject_id:
            description: The unique id provided to the entity being investigated. A subject can be a patient, human or non-human donor.
            type: string
            example: SUBJECT ID is an alphanumeric string that is globally unique identifier for the entity being investigated.
          event_id:
            description: Primary key or unique identifier for a event
            type: string
            example: E001
          event_type:
            description: Describing the events occurence for a patient
            type: string
            example: Diagnosis
            enum:
            - Encounter
            - Treatment
            - Procedure
@endyaml