@startyaml Publication
  Publication:
    description: Describes the publication related information such as abstract, authors, PUBMED ID and the publication link. 
    properties:
      project_id:
        description: Primary key or unique identifier for a project
        type: string
        example: P034
      abstract:
        description: Abstract of the publication associated with the dataset.
        type: string
        example: Background - The identification of novel therapeutic strategies to overcome resistance...
      authors:
        description: List of authors for the associated publication as given in the APA format
        type: string
        example: Puyalto, A., Rodríguez-Remírez, M., López, I., Macaya, I.
      journal:
        description: Journal in which the associated study was published
        type: string
        example: Molecular Cancer
      publication_link:
        description: Link to the publication associated with the dataset.
        type: string
        format: alphanumeric
        example: https://pubmed.ncbi.nlm.nih.gov/38643157/
      publication_title:
        description: Title of the publication associated with the dataset
        type: string
        example: Trametinib sensitizes KRAS-mutant lung adenocarcinoma tumors to PD-1/PD-L1 axis blockade via Id1 downregulation
      publication_year:
        description: Year in which the dataset was published
        type: integer
        format: numeric
        example: 2023
        lower_limit: 1900
        units:
          description: Unit is a quantity of constant magnitude which is used to measure the magnitudes of other quantities of the same manner
          uom: year
          encoding: UTF-8
      pubmed_id:
        description: Unique PUBMED identifier of the publication associated with the dataset
        type: integer
        format: numeric
        example: 38643157
      total_number_of_cells:
        description: Total number of cells present in a dataset
        type: integer
        format: numeric
        example: 150000
        lower_limit: 0.0
@endyaml